version: '3.1'

services:
  reverse_contact.app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reverse_contact.app
    env_file:
      - .env
    ports:
      - 5084:5084
    volumes:
      - ./backend/data:/app/data